(function(){var d;(function(){var f,h=navigator.userAgent.toLowerCase().indexOf("like mac os x")!=-1?!0:!1;typeof _tosR!="undefined"?d=window._tosR:(d=window._tosR=function(a){return new d.prototype.init(a)},typeof _tosWare=="undefined"&&(_tosWare={}),f=_tosWare,d.extend=function(a,b,c){c&&d.extend(a,c);for(var g in b)b.hasOwnProperty(g)&&(a[g]=b[g]);return a},d.extend(d,{getProtocol:function(){return location.protocol+"//"},joinParameters:function(a,b){var c=[];if(b==",")for(var d in a)a.hasOwnProperty(d)&&
Array.prototype.push.call(c,a[d]);else if(b=="&")for(var e in a)a.hasOwnProperty(e)&&Array.prototype.push.call(c,e+"="+a[e]);return c.join(b)},createCacheBuster:function(){return Math.floor((Math.random()+1)*1E9)},getCookieEnabled:function(){return navigator.cookieEnabled?1:0},getJavaEnabled:function(){return navigator.javaEnabled()?1:0},getHistoryLength:function(){var a=1;try{a=top.history.length}catch(b){a=history.length}return a},getInIframe:function(){var a=0;try{window!=top&&(a=0)}catch(b){}return a},
getFramesCount:function(a){for(var b=a.length,c=0;c<a.length;c++)b+=arguments.callee(a[c].frames);return b},getPluginLength:function(){return navigator.plugins.length||0},getMimeTypeLength:function(){return navigator.mimeTypes.length||0},getFlashVersion:function(){var a="0,0,0,0";try{navigator.plugins&&navigator.plugins["Shockwave Flash"]?a=navigator.plugins["Shockwave Flash"].description:window.ActiveXObject&&new ActiveXObject("ShockwaveFlash.ShockwaveFlash")&&(a=(new ActiveXObject("ShockwaveFlash.ShockwaveFlash")).GetVariable("$version"))}catch(b){}a=
a.match(/\d+/g);return a[0]},getPreviousUrl:function(){var a="";try{a=top.document.referrer}catch(b){}return encodeURIComponent(a)},getTopUrl:function(){var a="";try{a=top.document.location}catch(b){}return encodeURIComponent(a)},getType:function(a){a=Object.prototype.toString.call(a).toLowerCase().match(/\s([^\]]+)/);return a!=null?a[1]:"unknow"},getCharset:function(){var a="utf-8";return a=window.ActiveXObject?document.charset:document.characterSet},load:function(a,b,c,g){var e,f=/loaded|complete/i,
j="tos_acr_$"+d.createCacheBuster();b?(e=document.createElement("script"),e.type="text/javascript",e.async=1,e.id=j,e.src=a,document.getElementsByTagName("head")[0].appendChild(e)):(window.ActiveXObject&&(f=/complete/i),document.write('<script type="text/javascript" src="'+a+'" id="'+j+'"><\/script>'));if(e=d.$(j))e.onload=e.onreadystatechange=function(){if(!e.readyState||e.readyState.match(f))if(typeof c=="function"&&(c(),c=null),e&&e.parentNode)e.onload=e.onreadystatechange=null,e.parentNode.removeChild(e),
e=null};g&&setTimeout(function(){if(e)typeof c=="function"&&(c(),c=null),e.src="javascript:void(0)"},g)},req:function(a,b){d.load(a,1,b)},rtn:function(a){var b=a.aid,a=a.st,c=f["c"+b];c&&c.callback&&c.callback(a);a?(c&&c.dAd?(c.dAd(),d.setReturnFlag(b,0)):d.setReturnFlag(b,1),c&&c.sdct&&d.send(c.sdct)):(c&&c.ssct&&d.send(c.ssct),d.setReturnFlag(b,0))},setReturnFlag:function(a,b){if(b){window["_ACS86_ENABLE_"+a+"_"]=!1;window._ADCHINA_CONTROL_=!0;try{typeof rem_inv=="function"&&rem_inv()}catch(c){}}else{window["_ACS86_ENABLE_"+
a+"_"]=!0;window._ADCHINA_CONTROL_=!1;try{typeof com_show=="function"&&com_show()}catch(d){}}},send:function(a,b,c){var g,b=b||0,c=arguments.length<3?1:c;if(a)g=document.createElement(["img","iframe","script"][b]),g.src=c?a+(a.indexOf("?")>0?"&cb=":"?cb=")+d.createCacheBuster():a,g.style.display="none",document.body.insertBefore(g,document.body.firstChild)},$:function(a){return typeof a=="string"?document.getElementById(a):a},cookie:function(a,b,c){if(typeof b!=="undefined"){if(b===null)b="",c=c||
{},c.expires=new Date(1986,1,1);a=a+"="+b;c&&(c.expires&&(a+=";expires="+c.expires.toUTCString()),c.path&&(a+=";path="+c.path),c.domain&&(a+=";domain="+c.domain),c.secure&&(a+=";secure"));document.cookie=a}else return RegExp(";?"+a+"=([^;]*);?").test(document.cookie)?decodeURIComponent(RegExp.$1):null},element:function(a,b,c,g){a=document.createElement(a);if(b)for(var e in b)a.setAttribute(e,b[e]);c&&d.css(a,c);if(g)a.innerHTML=g;return a},css:function(a,b){var c=d.$(a);if(typeof b=="string"){if(c.currentStyle)return c.currentStyle[b];
if(window.getComputedStyle)return document.defaultView.getComputedStyle(c,null)[b]}else if(typeof b=="object")for(var g in b)c.style[g]=b[g]},getClient:function(a){a=a.charAt(0).toUpperCase()+a.substr(1).toLowerCase();return document.compatMode=="BackCompat"?document.body["client"+a]:document.documentElement["client"+a]},getScroll:function(a){a=a.charAt(0).toUpperCase()+a.substr(1).toLowerCase();return document.documentElement["scroll"+a]||document.body["scroll"+a]},getPosition:function(a){var a=
d.$(a),b={left:0,top:0};if(a.getBoundingClientRect)b.left=Math.round(a.getBoundingClientRect().left+d.getScroll("left")-(document.documentElement.clientLeft||document.body.clientLeft||0)),b.top=Math.round(a.getBoundingClientRect().top+d.getScroll("top")-(document.documentElement.clientTop||document.body.clientTop||0));return b},getCurrentScript:function(){var a={script:null,last:!1},b;if(document.currentScript)a.script=document.currentScript;else{b=document.getElementsByTagName("script");if(/msie \d/i.test(navigator.userAgent))for(i=
b.length-1;i>=0;i--)if(b[i].readyState==="interactive"){a.script=b[i];break}if(!a.script)a.script=b[b.length-1],a.last=!0}return a},getScreenIndex:function(a,b,c){var g=0,e=d.getClient("height"),f=0,j=d.$("tos_acr_"+a),h=null;if(b&&d.$(b))f=d.getPosition(b).top;else if(c)f=c[0];else if(j)h=d.element("div",{id:"vs_anch_"+a},{border:"none",background:"none",margin:0,padding:0,fontSize:0,height:"1px",width:"1px",position:"absolute"}),j.parentNode.insertBefore(h,j),f=d.getPosition(h).top,h.parentNode.removeChild(h);
e&&(g=Math.ceil(f/e));return g},postMessage:function(a,b,c){var d="ch"+Math.ceil(Math.random()*1E8);b.chid=d;b.sender="tosm";c&&(f[d]=c);a.postMessage(b,"*")},addEvent:function(a,b,c){a.attachEvent?a.attachEvent("on"+b,c):a.addEventListener&&a.addEventListener(b,c,!1)},removeEvent:function(a,b,c){a.detachEvent?a.detachEvent("on"+b,c):a.removeEventListener&&a.removeEventListener(b,c,!1)},apply:function(a,b,c){c&&arguments.callee(a,c);if(a&&b&&typeof b=="object")for(var d in b)b.hasOwnProperty(d)&&
(a[d]=b[d]);return a}}),d.addEvent(window,"message",function(a){var a=a.data,b=a.ctr;if(b=="ware"){var c=a.sender,b=a.chid;if(c&&c=="tosm"&&f[b])f[b](a)}else if(b=="warea"||b=="warer"){var d=a.aid,c=a.method,a=a.params?a.params:[];if(d&&c&&(b=f[b=="warea"?"a"+d:"r"+d])&&b[c])try{b[c].apply(b,a)}catch(e){}}},!1),d.prototype={init:function(a){var b=this,c;if(a&&a.aid)c="tos_acr_"+a.aid,function(){var b=d.getCurrentScript(),e=b.script,b=b.last;if(!d.$(c)){if(b&&!a.async&&(document.write('<ins id="'+
c+'" style="display:none;"></ins>'),d.$(c)))return;b=document.createElement("ins");b.style.display="none";b.id=c;e.parentNode.insertBefore(b,e)}}(),b.timestamp=(new Date).getTime(),b.aid=a.aid,f["c"+b.aid]=a,f["r"+b.aid]=b,b.g(),function(){if(!window._acsent){window._acsent=!0;var a=document.createElement("iframe"),c=document.getElementsByTagName("script"),c=c[c.length-1];a.style.display="none";a.src=d.getProtocol()+b.getStaticBaseUrl()+"ac.htm";c.parentNode.insertBefore(a,c)}}()},info:function(a,
b){var c="c"+this.aid;typeof f=="undefined"&&(f={});f[c]||(f[c]={});typeof b!="undefined"&&(b===null?delete f[c][a]:f[c][a]=b);return f[c][a]},getParameters:function(){var a={},b=window.devicePixelRatio?screen.width*window.devicePixelRatio:screen.width,c=window.devicePixelRatio?screen.height*window.devicePixelRatio:screen.height,g=window.devicePixelRatio?screen.availWidth*window.devicePixelRatio:screen.availWidth,e=window.devicePixelRatio?screen.availHeight*window.devicePixelRatio:screen.availHeight;
a.aid=this.info("aid");a.ec=d.getCharset();a.fv=d.getFlashVersion();a.ifm=d.getInIframe();a.hl=d.getHistoryLength();a.fc=d.getFramesCount(frames);a.si=d.getScreenIndex(this.aid,this.info("destid"),this.info("coors"));a.sw=b;a.sh=c;a.asw=g;a.ash=e;a.ce=d.getCookieEnabled();a.je=d.getJavaEnabled();a.pt=1;if(d.getPluginLength()!=0)a.pl=d.getPluginLength();if(d.getMimeTypeLength()!=0)a.ml=d.getMimeTypeLength();if(this.info("sendtopurl")===1&&d.getTopUrl()!=""&&d.getInIframe())a.tu=d.getTopUrl();if(this.info("sendpreviousurl")===
1&&d.getPreviousUrl()!="")a.pu=d.getPreviousUrl();if(f.vid)a.vid=f.vid;a.lm=0;if(typeof window.orientation!="undefined"&&(a.lm=Math.abs(window.orientation)==90?1:0,h&&a.lm))a.sw=c,a.sh=b,a.asw=e,a.ash=g;a.jsv=this.jsv;a.cb=d.createCacheBuster();return d.joinParameters(a,"&")},tlsReady:function(){var a=this;a.tlsHasReady=1;d.postMessage(a.info("tlsbridge").contentWindow,{ctr:"getCookie"},function(b){a.getCustomCookieCallback(b.data)})},getCustomCookie:function(a){var b;this.getCustomCookieCallback=
a;if(this.tlsHasReady)this.tlsReady();else if(!this.info("tlsbridge"))b=document.createElement("iframe"),b.style.display="none",b.src=d.getProtocol()+this.getStaticBaseUrl()+"tls.htm#"+this.aid,d.addEvent(b,"load",function(){d.removeEvent(b,"load",arguments.callee)}),document.body.insertBefore(b,document.body.firstChild),this.info("tlsbridge",b)},getServerUrl:function(){return d.getProtocol()+this.getBaseUrl()+"a.htm?"},getBaseUrl:function(){return this.info("serverbaseurl")?this.info("serverbaseurl"):
this.getLBUrl()},getStaticBaseUrl:function(){return this.info("staticbaseurl")?this.info("staticbaseurl"):this.info("staticbaseurl","static.mlt01.com/")},getLBUrl:function(){return this.info("serverbaseurl","a.mlt01.com/")},g:function(a,b){var c=this,g=function(){};c.info("async")==1&&h&&!f.vid?c.getCustomCookie(function(e){if(e&&e.vid)f.vid=e.vid;d.load(a||c.getServerUrl()+c.getParameters(),b||c.info("async"),g,1E4)}):d.load(a||c.getServerUrl()+c.getParameters(),b||c.info("async"),g,1E4)},jsv:1},
d.prototype.init.prototype=d.prototype)})();(function(){var f={aid:0,async:1,sendpreviousurl:1,sendtopurl:1,serverbaseurl:"a.mlt01.com/",staticbaseurl:"static.mlt01.com/"},h={};if(typeof window.tosAdspaceInfo=="object"&&tosAdspaceInfo&&tosAdspaceInfo.aid)d.apply(h,tosAdspaceInfo,f),d(h),window.tosAdspaceInfo=null})()})();
